apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  hostPID: true
  hostIPC: true
  hostNetwork: true
  containers:
    - image: ubuntu:jammy
      name: ubuntu
      command: ["tail"]
      args: ["-f", "/dev/null"]
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /host
          name: root
  volumes:
    - name: root
      hostPath:
        path: /
