apiVersion: v1
kind: Pod
metadata:
  name: nsenter
spec:
  hostPID: true
  terminationGracePeriodSeconds: 1
  containers:
    - image: ubuntu:jammy
      name: nsenter
      command: ["tail", "-f", "/dev/null"]
      securityContext:
        privileged: true
