apiVersion: v1
kind: Pod
metadata:
  name: image-volume
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: volume
      mountPath: /volume
  volumes:
  - name: volume
    image:
      reference: registry.k8s.io/kube-apiserver:v1.32.1
      pullPolicy: IfNotPresent
