apiVersion: v1
kind: Pod
metadata:
  name: image-volume
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: volume
      mountPath: /volume
  volumes:
  - name: volume
    image:
      reference: quay.io/crio/artifact:v1
      pullPolicy: IfNotPresent
