apiVersion: v1
kind: Pod
metadata:
  name: my-node
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - name: my-node
      image: ghcr.io/loft-sh/vm-container
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumeMounts:
        - name: run
          mountPath: /run
        - name: var-containerd
          mountPath: /var/lib/containerd
        - name: var-kubelet
          mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
        - name: var-vcluster
          mountPath: /var/lib/vcluster
  volumes:
    - name: var-kubelet
      emptyDir: {}
    - name: var-containerd
      emptyDir: {}
    - name: var-vcluster
      emptyDir: {}
    - name: run
      emptyDir: {}
