apiVersion: v1
kind: Pod
metadata:
  name: nginx-pvc-subpath
spec:
  containers:
    - name: app-container
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: pvc-volume
          subPath: html
  volumes:
    - name: pvc-volume
      persistentVolumeClaim:
        claimName: example-pvc-subpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc-subpath
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
