apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: postgres.my-postgres.credentials.postgresql.acid.zalan.do
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
