apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-vm
spec:
  runStrategy: Always
  dataVolumeTemplates:
    - metadata:
        name: data
      spec:
        pvc:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
        source:
          registry:
            url: docker://quay.io/containerdisks/ubuntu:22.04
  template:
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 4Gi
        devices:
          networkInterfaceMultiqueue: true
          disks:
            - name: containervolume
              disk: { bus: virtio }
            - name: cloudinit
              disk: { bus: virtio }
          interfaces:
            - name: default
              masquerade: {}
              ports:
                - name: ssh
                  port: 22
      networks:
        - name: default
          pod: {}
      evictionStrategy: External
      volumes:
        - name: containervolume
          dataVolume:
            name: data
        - name: cloudinit
          cloudInitNoCloud:
            userData: |
              #cloud-config
              users:
                - name: ubuntu
                  groups: sudo
                  shell: /bin/bash
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  ssh_authorized_keys:
                  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICcbmrkvMlIMashTKWRZAml8dxQEhQBhlWBs76MFGIpc fab.kramm@googlemail.com
