apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com
spec:
  secretName: example-com-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  commonName: example.com
  dnsNames:
  - www.example.com
